name: Update terms and conditions

on: workflow_dispatch

jobs:
  publishStatut:
    runs-on: ubuntu-latest
    env:
      WEBHOOK: ${{ secrets.WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn start
